apiVersion: apps/v1
kind: Deployment
metadata:
  name: celebrity-detector-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celebrity-detector-app
  template:
    metadata:
      labels:
        app: celebrity-detector-app
    spec:
      containers:
      - name: celebrity-detector-app
        image: us-central1-docker.pkg.dev/ozon-26aad/celebrity-detector/celebrity-detector-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: celebrity-detector-secrets
              key: GROQ_API_KEY

---

apiVersion: v1
kind: Service
metadata:
  name: celebrity-detector-service
spec:
  selector:
    app: celebrity-detector-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer